version: '3'
services:
  # MongoDB Service untuk OrderService
  db-order:
    image: mongo
    container_name: db-order
    ports:
      - '27017:27017'       # expose lokal → container
    volumes:
      - ./data/db-order:/data/db

  # RabbitMQ untuk komunikasi antar service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'         # port untuk koneksi AMQP
      - '15672:15672'       # port untuk UI management (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # Order Service (NestJS App)
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - '3000:3000'
    env_file:
      - ./order-service/.env
    depends_on:
      - db-order
      - rabbitmq

  # Kitchen Service (NestJS App)
  kitchen-service:
    build: ./kitchen-service
    container_name: kitchen-service
    ports:
      - '3001:3001'
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq

  # Notification Service (NestJS App)
  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - '3002:3002'
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq